// Sn2FrameCppExport.cpp — first-pass frame capture → C++ source emitter.
//
// Architecture (mirrors RenderDoc's util/automation/export_cpp.py):
//   1. Record D3D12 calls into an in-memory chunk list during one frame
//   2. On Present, walk chunks and emit C++ that replicates the sequence
//
// This is a SCOPED implementation — it captures CBV binds + draws + dispatches
// + PSO creates + resource creates + present. Other chunks emit as TODOs.

#include "Sn2FrameCppExport.hpp"

#include <atomic>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <mutex>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>

#include <spdlog/spdlog.h>

namespace sn2_frame_cpp_export {

namespace {

enum class Chunk : uint8_t {
    CreateCommittedResource,
    CreateGraphicsPso,
    CreateComputePso,
    DrawIndexed,
    Dispatch,
    SetGraphicsRootCbv,
    SetComputeRootCbv,
    Present,
};

struct Event {
    Chunk kind;
    uint64_t timestamp_ns{};
    // Generic payload — union by chunk kind.
    void* p0{};
    void* p1{};
    void* p2{};
    uint64_t u0{};
    uint64_t u1{};
    uint64_t u2{};
    uint32_t v[6]{};
};

struct State {
    std::atomic<bool> recording{false};
    std::atomic<bool> armed{false};
    std::atomic<uint64_t> present_count{0};
    std::mutex mu;
    std::vector<Event> events;
    std::unordered_map<void*, std::string> resource_names;
};

State& state() {
    static State s;
    return s;
}

std::string& dir() {
    static std::string s = []() -> std::string {
        char buf[2048]{};
        const auto len = GetEnvironmentVariableA("UEVR_SN2_FRAME_CAPTURE_DIR", buf, sizeof(buf));
        if (len == 0 || len >= sizeof(buf)) return std::string{};
        return std::string{buf, len};
    }();
    return s;
}

uint64_t trigger_frame() {
    static const uint64_t n = []() -> uint64_t {
        char buf[64]{};
        const auto len = GetEnvironmentVariableA("UEVR_SN2_FRAME_CAPTURE_TRIGGER", buf, sizeof(buf));
        if (len == 0 || len >= sizeof(buf)) return 300;
        std::string s{buf, len};
        if (s.rfind("frame=", 0) == 0) {
            return std::strtoull(s.c_str() + 6, nullptr, 0);
        }
        return 300;
    }();
    return n;
}

void emit_capture() {
    auto& s = state();
    std::scoped_lock _{s.mu};
    if (s.events.empty()) return;
    if (dir().empty()) return;
    std::error_code ec;
    std::filesystem::create_directories(dir(), ec);

    const std::string main_path  = dir() + "\\main.cpp";
    const std::string frame_path = dir() + "\\capture_frame.cpp";
    const std::string cmake_path = dir() + "\\CMakeLists.txt";
    const std::string readme_path = dir() + "\\README.md";

    // main.cpp — entry point. Loads the saved blobs and replays events.
    std::ofstream main_out{main_path};
    main_out << R"CPP(// Auto-generated by Sn2FrameCppExport — UEVR's RenderDoc-equivalent frame
// capture. Replays one frame's D3D12 calls against a fresh device/swapchain.
//
// Build: cmake -B build && cmake --build build --config Release
// Run:   build\Release\frame_capture.exe

#include <windows.h>
#include <d3d12.h>
#include <dxgi1_6.h>
#include <wrl/client.h>
#include <cstdio>

extern void RecordFrame(ID3D12Device* device, ID3D12CommandQueue* queue,
                        ID3D12GraphicsCommandList* cl, IDXGISwapChain3* swap);

int main() {
    using Microsoft::WRL::ComPtr;
    ComPtr<IDXGIFactory6> factory;
    CreateDXGIFactory2(0, IID_PPV_ARGS(&factory));
    ComPtr<IDXGIAdapter1> adapter;
    factory->EnumAdapters1(0, &adapter);

    ComPtr<ID3D12Device> device;
    D3D12CreateDevice(adapter.Get(), D3D_FEATURE_LEVEL_11_0, IID_PPV_ARGS(&device));

    D3D12_COMMAND_QUEUE_DESC qd{};
    qd.Type = D3D12_COMMAND_LIST_TYPE_DIRECT;
    ComPtr<ID3D12CommandQueue> queue;
    device->CreateCommandQueue(&qd, IID_PPV_ARGS(&queue));

    ComPtr<ID3D12CommandAllocator> alloc;
    device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT, IID_PPV_ARGS(&alloc));
    ComPtr<ID3D12GraphicsCommandList> cl;
    device->CreateCommandList(0, D3D12_COMMAND_LIST_TYPE_DIRECT,
                              alloc.Get(), nullptr, IID_PPV_ARGS(&cl));
    cl->Close();

    // TODO: create swapchain matching the captured frame's dimensions.
    IDXGISwapChain3* swap = nullptr;

    RecordFrame(device.Get(), queue.Get(), cl.Get(), swap);

    printf("done.\n");
    return 0;
}
)CPP";

    // capture_frame.cpp — per-event replay
    std::ofstream frame_out{frame_path};
    frame_out << "// Auto-generated by Sn2FrameCppExport. Events: " << s.events.size() << "\n";
    frame_out << "#include <d3d12.h>\n";
    frame_out << "#include <cstdio>\n\n";
    frame_out << "void RecordFrame(ID3D12Device* device, ID3D12CommandQueue* queue,\n";
    frame_out << "                 ID3D12GraphicsCommandList* cl, IDXGISwapChain3* swap) {\n";
    size_t event_i = 0;
    for (const auto& e : s.events) {
        switch (e.kind) {
        case Chunk::CreateCommittedResource:
            frame_out << "    /* event " << event_i << ": CreateCommittedResource res=0x"
                      << std::hex << reinterpret_cast<uintptr_t>(e.p0) << std::dec << " */\n";
            break;
        case Chunk::CreateGraphicsPso:
            frame_out << "    /* event " << event_i << ": CreateGraphicsPipelineState pso=0x"
                      << std::hex << reinterpret_cast<uintptr_t>(e.p0) << std::dec << " */\n";
            break;
        case Chunk::CreateComputePso:
            frame_out << "    /* event " << event_i << ": CreateComputePipelineState pso=0x"
                      << std::hex << reinterpret_cast<uintptr_t>(e.p0) << std::dec << " */\n";
            break;
        case Chunk::DrawIndexed:
            frame_out << "    cl->DrawIndexedInstanced("
                      << e.v[0] << ", " << e.v[1] << ", "
                      << e.v[2] << ", " << static_cast<int>(e.v[3]) << ", " << e.v[4] << ");\n";
            break;
        case Chunk::Dispatch:
            frame_out << "    cl->Dispatch(" << e.v[0] << ", " << e.v[1] << ", " << e.v[2] << ");\n";
            break;
        case Chunk::SetGraphicsRootCbv:
            frame_out << "    cl->SetGraphicsRootConstantBufferView("
                      << e.v[0] << ", 0x" << std::hex << e.u0 << std::dec << "ull);\n";
            break;
        case Chunk::SetComputeRootCbv:
            frame_out << "    cl->SetComputeRootConstantBufferView("
                      << e.v[0] << ", 0x" << std::hex << e.u0 << std::dec << "ull);\n";
            break;
        case Chunk::Present:
            frame_out << "    /* event " << event_i << ": Present */\n";
            frame_out << "    /* swap->Present(0, 0); */\n";
            break;
        }
        ++event_i;
    }
    frame_out << "}\n";

    // CMakeLists.txt
    std::ofstream cmake_out{cmake_path};
    cmake_out << "cmake_minimum_required(VERSION 3.15)\n"
              << "project(frame_capture)\n"
              << "set(CMAKE_CXX_STANDARD 17)\n"
              << "add_executable(frame_capture main.cpp capture_frame.cpp)\n"
              << "target_link_libraries(frame_capture PRIVATE d3d12 dxgi)\n";

    // README.md
    std::ofstream readme_out{readme_path};
    readme_out << "# Sn2 Frame Capture\n\n"
               << "Auto-generated single-frame D3D12 replay.\n\n"
               << "Events captured: " << s.events.size() << "\n";

    // events.json — machine-parseable event log for Python tooling.
    // Mirrors capture_frame.cpp but lets us slice/dice events offline.
    const std::string events_path = dir() + "\\events.json";
    std::ofstream events_out{events_path};
    events_out << "{\n  \"event_count\": " << s.events.size() << ",\n  \"events\": [\n";
    size_t i = 0;
    for (const auto& e : s.events) {
        events_out << "    {";
        events_out << "\"i\":" << i;
        events_out << ",\"kind\":\"";
        switch (e.kind) {
            case Chunk::CreateCommittedResource: events_out << "CreateCommittedResource"; break;
            case Chunk::CreateGraphicsPso:       events_out << "CreateGraphicsPipelineState"; break;
            case Chunk::CreateComputePso:        events_out << "CreateComputePipelineState"; break;
            case Chunk::DrawIndexed:             events_out << "DrawIndexedInstanced"; break;
            case Chunk::Dispatch:                events_out << "Dispatch"; break;
            case Chunk::SetGraphicsRootCbv:      events_out << "SetGraphicsRootCBV"; break;
            case Chunk::SetComputeRootCbv:       events_out << "SetComputeRootCBV"; break;
            case Chunk::Present:                 events_out << "Present"; break;
        }
        events_out << "\"";
        switch (e.kind) {
        case Chunk::CreateCommittedResource:
        case Chunk::CreateGraphicsPso:
        case Chunk::CreateComputePso:
            events_out << ",\"ptr\":" << reinterpret_cast<uintptr_t>(e.p0);
            break;
        case Chunk::DrawIndexed:
            events_out << ",\"index_count\":" << e.v[0]
                       << ",\"instance_count\":" << e.v[1]
                       << ",\"start_index\":" << e.v[2]
                       << ",\"base_vertex\":" << static_cast<int>(e.v[3])
                       << ",\"start_instance\":" << e.v[4];
            break;
        case Chunk::Dispatch:
            events_out << ",\"x\":" << e.v[0]
                       << ",\"y\":" << e.v[1]
                       << ",\"z\":" << e.v[2];
            break;
        case Chunk::SetGraphicsRootCbv:
        case Chunk::SetComputeRootCbv:
            events_out << ",\"root\":" << e.v[0]
                       << ",\"gpu_va\":" << e.u0;
            break;
        case Chunk::Present:
            break;
        }
        events_out << "}" << (i + 1 < s.events.size() ? "," : "") << "\n";
        ++i;
    }
    events_out << "  ]\n}\n";

    SPDLOG_INFO("[SN2-FrameCppExport] wrote {} events to {}", s.events.size(), dir());
    s.events.clear();
    s.recording.store(false, std::memory_order_release);
    s.armed.store(false, std::memory_order_release);
}

}  // namespace

bool env_enabled() {
    static const bool e = []() {
        return GetEnvironmentVariableW(L"UEVR_SN2_FRAME_CAPTURE_DIR", nullptr, 0) > 0;
    }();
    return e;
}

const char* output_dir() { return dir().c_str(); }

void arm_capture() {
    if (!env_enabled()) return;
    state().armed.store(true, std::memory_order_release);
}

bool is_recording() {
    return state().recording.load(std::memory_order_acquire);
}

void on_create_committed_resource(const D3D12_HEAP_PROPERTIES*, D3D12_HEAP_FLAGS,
                                  const D3D12_RESOURCE_DESC* desc,
                                  D3D12_RESOURCE_STATES, ID3D12Resource* res) {
    if (!is_recording()) return;
    auto& s = state();
    std::scoped_lock _{s.mu};
    Event e{Chunk::CreateCommittedResource};
    e.p0 = res;
    s.events.push_back(e);
}

void on_create_graphics_pipeline_state(const D3D12_GRAPHICS_PIPELINE_STATE_DESC*,
                                       ID3D12PipelineState* pso) {
    if (!is_recording()) return;
    auto& s = state();
    std::scoped_lock _{s.mu};
    Event e{Chunk::CreateGraphicsPso};
    e.p0 = pso;
    s.events.push_back(e);
}

void on_create_compute_pipeline_state(const D3D12_COMPUTE_PIPELINE_STATE_DESC*,
                                      ID3D12PipelineState* pso) {
    if (!is_recording()) return;
    auto& s = state();
    std::scoped_lock _{s.mu};
    Event e{Chunk::CreateComputePso};
    e.p0 = pso;
    s.events.push_back(e);
}

void on_draw_indexed_instanced(ID3D12GraphicsCommandList*,
                               UINT idx, UINT inst, UINT si, INT bv, UINT sii) {
    if (!is_recording()) return;
    auto& s = state();
    std::scoped_lock _{s.mu};
    Event e{Chunk::DrawIndexed};
    e.v[0] = idx; e.v[1] = inst; e.v[2] = si; e.v[3] = static_cast<uint32_t>(bv); e.v[4] = sii;
    s.events.push_back(e);
}

void on_dispatch(ID3D12GraphicsCommandList*, UINT x, UINT y, UINT z) {
    if (!is_recording()) return;
    auto& s = state();
    std::scoped_lock _{s.mu};
    Event e{Chunk::Dispatch};
    e.v[0] = x; e.v[1] = y; e.v[2] = z;
    s.events.push_back(e);
}

void on_set_graphics_root_cbv(ID3D12GraphicsCommandList*,
                              UINT root, D3D12_GPU_VIRTUAL_ADDRESS va) {
    if (!is_recording()) return;
    auto& s = state();
    std::scoped_lock _{s.mu};
    Event e{Chunk::SetGraphicsRootCbv};
    e.v[0] = root; e.u0 = va;
    s.events.push_back(e);
}

void on_set_compute_root_cbv(ID3D12GraphicsCommandList*,
                             UINT root, D3D12_GPU_VIRTUAL_ADDRESS va) {
    if (!is_recording()) return;
    auto& s = state();
    std::scoped_lock _{s.mu};
    Event e{Chunk::SetComputeRootCbv};
    e.v[0] = root; e.u0 = va;
    s.events.push_back(e);
}

void on_present() {
    if (!env_enabled()) return;
    auto& s = state();
    const auto n = s.present_count.fetch_add(1, std::memory_order_relaxed) + 1;

    // If we're recording, this Present ends the captured frame.
    if (s.recording.load(std::memory_order_acquire)) {
        {
            std::scoped_lock _{s.mu};
            Event e{Chunk::Present};
            s.events.push_back(e);
        }
        emit_capture();
        return;
    }

    // Check trigger: armed via API, OR auto-arm at frame N.
    if (n == trigger_frame() || s.armed.load(std::memory_order_acquire)) {
        s.recording.store(true, std::memory_order_release);
        SPDLOG_WARN("[SN2-FrameCppExport] arming capture at present #{}", n);
    }
}

}  // namespace sn2_frame_cpp_export
