# Regenerates src/mods/vr/d3d12/DIBRShadersEmbedded.hpp from the DIBR HLSL sources.
# Run after editing src/mods/vr/d3d12/shaders/dibr_*.hlsl:
#   powershell -ExecutionPolicy Bypass -File tools/embed_dibr_shaders.ps1
#
# Sources are emitted as arrays of raw string literal chunks (<= 12000 bytes each,
# split at line boundaries) to stay under MSVC's per-literal limits, and joined at
# runtime by the accessor functions.
$ErrorActionPreference = 'Stop'

$root = Split-Path $PSScriptRoot -Parent
$shaderDir = Join-Path $root 'src\mods\vr\d3d12\shaders'
$outPath = Join-Path $root 'src\mods\vr\d3d12\DIBRShadersEmbedded.hpp'

$shaders = @(
    @{ File = 'dibr_inverse.hlsl';  Name = 'dibr_inverse'  },
    @{ File = 'dibr_yoro.hlsl';     Name = 'dibr_yoro'     },
    @{ File = 'dibr_raymarch.hlsl'; Name = 'dibr_raymarch' }
)

$maxChunk = 12000
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// Auto-generated by tools/embed_dibr_shaders.ps1 -- DO NOT EDIT BY HAND.')
[void]$sb.AppendLine('// Regenerate after editing src/mods/vr/d3d12/shaders/dibr_*.hlsl.')
[void]$sb.AppendLine('#pragma once')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('#include <string>')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('namespace vrmod::dibr_shaders {')

foreach ($s in $shaders) {
    $path = Join-Path $shaderDir $s.File
    $text = [System.IO.File]::ReadAllText($path)
    if ($text.Contains(')DIBR"')) { throw "$($s.File) contains the raw-string delimiter sequence" }

    $chunks = [System.Collections.Generic.List[string]]::new()
    $current = [System.Text.StringBuilder]::new()
    foreach ($line in ($text -split "(?<=`n)")) {
        if ($current.Length + $line.Length -gt $maxChunk -and $current.Length -gt 0) {
            $chunks.Add($current.ToString())
            [void]$current.Clear()
        }
        [void]$current.Append($line)
    }
    if ($current.Length -gt 0) { $chunks.Add($current.ToString()) }

    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("// $($s.File) ($($text.Length) bytes, $($chunks.Count) chunks)")
    [void]$sb.AppendLine("inline const char* const g_$($s.Name)_chunks[] = {")
    foreach ($c in $chunks) {
        [void]$sb.AppendLine("R`"DIBR($c)DIBR`",")
    }
    [void]$sb.AppendLine('};')
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("inline std::string $($s.Name)_source() {")
    [void]$sb.AppendLine("    std::string out{};")
    [void]$sb.AppendLine("    for (const char* chunk : g_$($s.Name)_chunks) { out += chunk; }")
    [void]$sb.AppendLine("    return out;")
    [void]$sb.AppendLine('}')
}

[void]$sb.AppendLine('} // namespace vrmod::dibr_shaders')
[System.IO.File]::WriteAllText($outPath, $sb.ToString())
Write-Output "Wrote $outPath ($((Get-Item $outPath).Length) bytes)"
