"""
generate_sn2_dup_cfg.py

Builds E:/Github/UEVRJ/artifacts/sn2_dup_cfg.json matching the
uevr.sn2.dup_config.v1 schema (consumed by src/hooks/Sn2DupConfigFile.hpp).

Inputs:
- artifacts/sn2_pso_rootsig_graph.json: PSO -> RS uid graph
- E:/tmp_dir/sn2_round3/task4_v2_results.json: truly LEFT-only PSO inventory
- artifacts/left_only_dxil/INDEX.json: per-PSO PS/VS/CS CRC + reads_view_cbuffer flag
- cpp_export PSO index: stages metadata
- Empirical state_events analysis (Round 4): per-PSO View CB root params at the
  known eye-bound offsets (1075200 LEFT / 1064960 RIGHT, res_uid 3668).

Output: per-PS-CRC dup config with view_cb_roots (where known), mode, note.
Drop the result in as the value of UEVR_SN2_DUP_CONFIG_FILE.
"""
import json
import os
from collections import Counter

# Paths
DXIL_INDEX = r'E:/Github/UEVRJ/artifacts/left_only_dxil/INDEX.json'
INV = r'E:/tmp_dir/sn2_round3/task4_v2_results.json'
RSG = r'E:/Github/UEVRJ/artifacts/sn2_pso_rootsig_graph.json'
PSO_DB = (r'E:/Github/Subnautica 2/captures/nsight_cpp_2025_replay_saved_20260521_090747/'
          r'CppCaptures/ngfx-replay__2026_05_21__09_09_41/.ngfxmcp_cpp2025_pso_index.json')
VIEW_ROOTS_FILE = r'E:/tmp_dir/sn2_round4/leftonly_pso_view_roots.json'

OUT = r'E:/Github/UEVRJ/artifacts/sn2_dup_cfg.json'

with open(DXIL_INDEX) as f:
    bundle = json.load(f)
with open(INV) as f:
    inv = json.load(f)
with open(PSO_DB) as f:
    pso_db = json.load(f)
pso_lookup = {p['pso']: p for p in pso_db['psos']}
with open(VIEW_ROOTS_FILE) as f:
    view_roots = json.load(f)  # {pso_str: [roots]}

entries = {}
schema = {
    'schema': 'uevr.sn2.dup_config.v1',
    'description': 'SN2 stereo-VR LEFT-only PSO duplication config. '
                   'Generated by tools/generate_sn2_dup_cfg.py from Round 4 analysis '
                   '(Nsight cpp_export 2026-05-21). Eye-offsets: LEFT=1075200, RIGHT=1064960, '
                   'View pool res_uid 3668, delta=-10240.',
    'default_view_cb_delta': -10240,
    'default_view_cb_roots': [3],
    'entries': entries,
}

skipped = []
for b in bundle:
    pso = b['pso']
    ps_crc_str = b.get('ps_crc')
    cs_crc_str = b.get('cs_crc')
    rs = b.get('root_sig')
    L_draws = b.get('L_draws', 0)
    reads_view = b.get('reads_view_cbuffer', False)
    has_slw = b.get('has_slw_keyword', False)
    rt_format = b.get('RT_format', '')

    crc_str = ps_crc_str or cs_crc_str
    if not crc_str:
        skipped.append({'pso': pso, 'reason': 'no PS or CS CRC'})
        continue

    crc_key = f'0x{crc_str.lower()}'
    roots = view_roots.get(str(pso), [])

    # Decide mode:
    # - viewport_shift: PS reads View cbuffer => viewport+CB swap on RIGHT
    # - view_cb_only:   PS does not read View cbuffer; CB-only re-issue on RIGHT
    if reads_view and roots:
        mode = 'viewport_shift'
        note_parts = [
            f'PS CRC, reads View cbuffer, RS{rs}, {L_draws} LEFT-only draws',
            f'RT={rt_format}',
            f'View CB empirically at root param(s) {roots}',
        ]
    elif reads_view and not roots:
        mode = 'viewport_shift'
        note_parts = [
            f'PS CRC, reads View cbuffer, RS{rs}, {L_draws} LEFT-only draws',
            f'RT={rt_format}',
            'NO empirical View root match - falling back to default_view_cb_roots',
        ]
    else:
        mode = 'view_cb_only'
        note_parts = [
            f'PS CRC, does NOT read View cbuffer, RS{rs}, {L_draws} LEFT-only draws',
            f'RT={rt_format}',
            'CB-only mode: no root remap needed; just re-issue on RIGHT viewport',
        ]

    if has_slw:
        note_parts.append('SLW keyword detected (Subnautica-specific)')

    # Coalesce duplicate CRCs (same PS used by multiple PSOs)
    existing = entries.get(crc_key)
    if existing is not None:
        # Promote to multi-PSO entry; concatenate metadata
        existing_psos = existing.get('psos') or [existing.get('pso')]
        existing_psos = [p for p in existing_psos if p is not None]
        if pso not in existing_psos:
            existing_psos.append(pso)
        existing['psos'] = sorted(existing_psos)
        existing.pop('pso', None)
        existing['L_draws'] = existing.get('L_draws', 0) + L_draws
        existing['rt_formats'] = sorted(set((existing.get('rt_formats') or [existing.get('rt_format')] if existing.get('rt_format') else []) + [rt_format]))
        existing.pop('rt_format', None)
        # Append note about this additional PSO
        existing['note'] = existing.get('note', '') + ' ;; ALSO PSO ' + str(pso) + ': ' + ' | '.join(note_parts)
        if roots:
            merged_roots = sorted(set((existing.get('view_cb_roots') or []) + [int(r) for r in roots]))
            existing['view_cb_roots'] = merged_roots
        continue

    entry = {
        'mode': mode,
        'pso': pso,
        'root_sig': rs,
        'rt_format': rt_format,
        'L_draws': L_draws,
        'reads_view_cbuffer': reads_view,
        'note': ' | '.join(note_parts),
    }
    if roots:
        entry['view_cb_roots'] = sorted([int(r) for r in roots])

    entries[crc_key] = entry


def main():
    print(f'Total entries: {len(entries)}')
    print(f'Skipped: {len(skipped)} ({skipped})')
    mode_counts = Counter(e['mode'] for e in entries.values())
    print(f'Modes: {dict(mode_counts)}')
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w') as f:
        json.dump(schema, f, indent=2)
    print(f'Wrote {OUT}')
    with open(OUT) as f:
        re_loaded = json.load(f)
    print(f'Verified: schema={re_loaded["schema"]}, entries={len(re_loaded["entries"])}')


if __name__ == '__main__':
    main()
